name: Mon GitHub pipeline

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Ansible
      env:
        FTP_PASSWORD_DEV: "${{ secrets.FTP_PASSWORD_DEV }}"
      run: |
        cd ansible
        ansible-playbook \
          -vvv \
          --inventory inventory/DEV \
          --extra-vars FTP_PASSWORD_DEV="${FTP_PASSWORD_DEV}" \
          test.yml
